# Generated by Django 5.2.3 on 2025-07-01 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('faxcode', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='baseapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_type', models.CharField(choices=[('capital', 'Capital'), ('revenue', 'Revenue')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('indent_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('annexure_x', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('annexure_y', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('gem_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('financial_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.category')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.location')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.subcategory')),
            ],
            options={
                'unique_together': {('name', 'category', 'location')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('manpower_type', models.CharField(choices=[('exe', 'Executive'), ('mr', 'MR'), ('dr', 'DR')], default='exe', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.location')),
                ('survey_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='baseapp.surveyinfo')),
                ('system_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.systemmodel')),
            ],
            options={
                'unique_together': {('survey_info', 'department', 'system_model')},
            },
        ),
    ]
